import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';
import { ThemeProvider } from '@/components/theme-provider';

const inter = Inter({ subsets: ['latin'] });

export const Metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return (
    <>
      <div className='{inter.className}'>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disalbeTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </div>
    </>
  );
}
